# This workflow will install ...

name: Application Runner

on:
#  schedule:
#    - cron: "0 13 1 1 *" #run on first of January every year, 13:00
  [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  run-creation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 -m pip install -e .
    - name: run the script
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python3 -m GarbageCalendar Ingolstadt Schoberstr. 26
    - name: archive created file
      uses: actions/upload-artifact@v3
      with:
        name: calendar_xml
        path: garbageCalendar*.xls
        retention-days: 1
    - name: Download created file
      uses: actions/download-artifact@v3
      with:
        name: calendar_xml

